### ISSUE TITLE
completely new to this, I have GitHub, python and pip, need help

### ISSUE THREAD

**Issue by psydhawwrth** [lucidrains/stylegan2-pytorch#1]
Hey, I only have a little coding experience but I'm trying this out. I have a virtualenv open and I did the first command but it comes up as "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'". I have the requirements file in the same place as where I originally downloaded it, am I doing something wrong? on Mac

**Comment by lucidrains** [comment]
hey, you need to be in the directory of the project! did you git clone the project?

**Comment by psydhawwrth** [comment]
ok so I was able to get to that, but now at the last part when I'm doing the train command, I get this error: 

ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/Users/me/venv/lib/python3.7/site-packages/PIL/__init__.py)

I have no idea what this means or how to fix it.

**Comment by lucidrains** [comment]
ohh hmm, can you try a new virtual environment and run `pip install -r requirements.txt` again? i updated it with pillow

**Comment by lucidrains** [comment]
i turned it into a command line tool, can you try following the readme and reopen if you have any issues?

**Comment by psydhawwrth** [comment]
after the training command, "NameError: name 'tqdm' is not defined"

other than that everything is working great
