### ISSUE TITLE
Some information about training in the README.md

### ISSUE THREAD

**Issue by mynameisfiber** [lucidrains/stylegan2-pytorch#10]
It'd be nice to have some details about how the example results were trained. In particular, I'd be interested to see:

- Were they trained with the default training parameters?
- How many epochs?
- How long did it take on what type of hardware?
- How big were the datasets?

Thanks so much!

**Comment by lucidrains** [comment]
Hi! If you are referring to the officially released models, you can find all the details for how they were trained at https://github.com/NVlabs/stylegan2 and in the paper itself

**Comment by mynameisfiber** [comment]
I was referring to the training parameters in order to re-create the images in the README. Were they generated using this repo?

**Comment by mynameisfiber** [comment]
I was referring to the images in the README. I assume they were generated with the code from this repo?

**Comment by lucidrains** [comment]
@mynameisfiber oh ok! the datasets used can be found in the reference section below. as for the training, image size was set at 256x256 with the rest of the settings unchanged, trained for about 3 days on one RTX 2080 Ti
