### ISSUE TITLE
conv2DMod forward

### ISSUE THREAD

**Issue by theoad** [lucidrains/stylegan2-pytorch#107]
Hi,
can someone explain the following line (line 339 in stylegan2_pytorch.py):
`weights = w2 * (w1 + 1)`
Why is there +1 here ? is it bias ?

Thanks

**Comment by lucidrains** [comment]
@theoad from this line! https://github.com/NVlabs/stylegan2/blob/master/training/networks_stylegan2.py#L99

**Comment by lzomedia** [comment]
i think it was because of the 2x matrice
