### ISSUE TITLE
Mixed precision training with APEX is a lot slower than fp32

### ISSUE THREAD

**Issue by n00mkrad** [lucidrains/stylegan2-pytorch#129]
When I add the fp16 flag, my VRAM usage drops, but the training speed slows down significantly, roughly doubling the time it takes to process one iteration.

Is there any way to fix this?

**Comment by lucidrains** [comment]
@n00mkrad so I had the chance to try converting some code over to the new amp module in Pytorch 1.6, but it resulted in doubling the time also, and worse, increased the ram usage by 500mb

**Comment by lucidrains** [comment]
@n00mkrad I think instead I'll work on getting multi-gpu training working this week

**Comment by lucidrains** [comment]
https://github.com/pytorch/pytorch/issues/40073
