### ISSUE TITLE
Train on a specific GPU?

### ISSUE THREAD

**Issue by athenawisdoms** [lucidrains/stylegan2-pytorch#132]
Hi, I have multiple GPU devices on my machine. Is it possible to specify to `stylegan2_pytorch` which CUDA device should be used to train the model? It is currently always using the first CUDA device.

Thank you!

**Comment by lucidrains** [comment]
@athenawisdoms yup there is! you need to know the id of your device (`nvidia-smi` then look for the # of your GPU). Then, you execute `stylegan2_pytorch` with the environmental variable specifying which devices you wish available

ex. only GPU devices 2 and 4 can be used

```bash
$ CUDA_VISIBLE_DEVICES=2,4 stylegan2_pytorch --data ./data
```

**Comment by athenawisdoms** [comment]
It works, thanks!
