### ISSUE TITLE
Question about accumulating g_ema and generator.

### ISSUE THREAD

**Issue by lioo717** [lucidrains/stylegan2-pytorch#135]
What's the purpose of accumulating g_ema and generator?
I didn't find the same trick in official version.
Could you explain it or offer the citation?
Thank you very much.

**Comment by lucidrains** [comment]
@lioo717 exponential moving averages is a technique used both in the official stylegan code, as well as many other GANs https://arxiv.org/abs/1806.04498

**Comment by lioo717** [comment]
Thanks very much for your reply.
