### ISSUE TITLE
Not able to continue training

### ISSUE THREAD

**Issue by phqmourao** [lucidrains/stylegan2-pytorch#136]
Hi,
I was successfully training a model for a few days on Google Colab.
Today I was unable to continue training.
Any help would be greatly appreciated.

stylegan2_pytorch --data /img --image-size 128 --network_capacity 32 --batch_size 8 --gradient_accumulate_every 4 --aug-prob 0.25 --dataset-aug-prob 0.5 --attn_layers [1,2] --learning_rate 2e-4

continuing from previous epoch - 42
Traceback (most recent call last):
  File "/usr/local/bin/stylegan2_pytorch", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/cli.py", line 157, in main
    fire.Fire(train_from_folder)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/cli.py", line 148, in train_from_folder
    run_training(0, 1, model_args, data, load_from, new, num_train_steps, name)
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/cli.py", line 52, in run_training
    model.load(load_from)
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 1104, in load
    self.GAN.load_state_dict(load_data['GAN'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for StyleGAN2:
	Missing key(s) in state_dict: "G.blocks.0.to_rgb.upsample.1.f", "G.blocks.1.to_rgb.upsample.1.f", "G.blocks.2.to_rgb.upsample.1.f", "G.blocks.3.to_rgb.upsample.1.f", "G.blocks.4.to_rgb.upsample.1.f", "D.blocks.0.downsample.0.f", "D.blocks.0.downsample.1.weight", "D.blocks.0.downsample.1.bias", "D.blocks.1.downsample.0.f", "D.blocks.1.downsample.1.weight", "D.blocks.1.downsample.1.bias", "D.blocks.2.downsample.0.f", "D.blocks.2.downsample.1.weight", "D.blocks.2.downsample.1.bias", "D.blocks.3.downsample.0.f", "D.blocks.3.downsample.1.weight", "D.blocks.3.downsample.1.bias", "D.blocks.4.downsample.0.f", "D.blocks.4.downsample.1.weight", "D.blocks.4.downsample.1.bias", "D.blocks.5.downsample.0.f", "D.blocks.5.downsample.1.weight", "D.blocks.5.downsample.1.bias", "GE.blocks.0.to_rgb.upsample.1.f", "GE.blocks.1.to_rgb.upsample.1.f", "GE.blocks.2.to_rgb.upsample.1.f", "GE.blocks.3.to_rgb.upsample.1.f", "GE.blocks.4.to_rgb.upsample.1.f", "D_aug.D.blocks.0.downsample.0.f", "D_aug.D.blocks.0.downsample.1.weight", "D_aug.D.blocks.0.downsample.1.bias", "D_aug.D.blocks.1.downsample.0.f", "D_aug.D.blocks.1.downsample.1.weight", "D_aug.D.blocks.1.downsample.1.bias", "D_aug.D.blocks.2.downsample.0.f", "D_aug.D.blocks.2.downsample.1.weight", "D_aug.D.blocks.2.downsample.1.bias", "D_aug.D.blocks.3.downsample.0.f", "D_aug.D.blocks.3.downsample.1.weight", "D_aug.D.blocks.3.downsample.1.bias", "D_aug.D.blocks.4.downsample.0.f", "D_aug.D.blocks.4.downsample.1.weight", "D_aug.D.blocks.4.downsample.1.bias", "D_aug.D.blocks.5.downsample.0.f", "D_aug.D.blocks.5.downsample.1.weight", "D_aug.D.blocks.5.downsample.1.bias". 
	Unexpected key(s) in state_dict: "D.blocks.0.downsample.weight", "D.blocks.0.downsample.bias", "D.blocks.1.downsample.weight", "D.blocks.1.downsample.bias", "D.blocks.2.downsample.weight", "D.blocks.2.downsample.bias", "D.blocks.3.downsample.weight", "D.blocks.3.downsample.bias", "D.blocks.4.downsample.weight", "D.blocks.4.downsample.bias", "D.blocks.5.downsample.weight", "D.blocks.5.downsample.bias", "D_aug.D.blocks.0.downsample.weight", "D_aug.D.blocks.0.downsample.bias", "D_aug.D.blocks.1.downsample.weight", "D_aug.D.blocks.1.downsample.bias", "D_aug.D.blocks.2.downsample.weight", "D_aug.D.blocks.2.downsample.bias", "D_aug.D.blocks.3.downsample.weight", "D_aug.D.blocks.3.downsample.bias", "D_aug.D.blocks.4.downsample.weight", "D_aug.D.blocks.4.downsample.bias", "D_aug.D.blocks.5.downsample.weight", "D_aug.D.blocks.5.downsample.bias".

**Comment by lucidrains** [comment]
@phqmourao It's probably because you updated the package to v1.x, which now contains some new modules. If you downgrade to the version you had when you started training, it should work fine

**Comment by phqmourao** [comment]
@lucidrains 
I downgrade to version 1.0.2 and the problem was solved.
pip install 'stylegan2_pytorch==1.0.2'
Thank you very much.
