### ISSUE TITLE
Why no bias added in Generator?

### ISSUE THREAD

**Issue by deeplearningfam** [lucidrains/stylegan2-pytorch#141]
Hi,

I was wondering why there is never a learned bias added in the generator? It seems like they do this in the original version.

Thanks!

Best,
Michael

**Comment by lucidrains** [comment]
@deeplearningfam oh oops, where did I miss the bias? I'll sneak it in there for the next update

**Comment by lucidrains** [comment]
hmm, i don't spot the difference, do reopen if you can point me where you see the discrepancy!
