### ISSUE TITLE
Issue running the code with the --generate label

### ISSUE THREAD

**Issue by albusdemens** [lucidrains/stylegan2-pytorch#15]
Hi, I am training an agent to generate 512x512 images and I am trying to display intermediate results using the `--generate` flag. It looks like something is off (see errors [here](https://gist.github.com/albusdemens/170905c5f565d318443e79d8f21dbb64)). Am I doing something wrong? The command I use is `stylegan2_pytorch --generate`.

**Comment by lucidrains** [comment]
@albusdemens Hi! When you generate, you have to supply the same network settings as you did when you trained. So the command you would execute would be along the lines of `stylegan2_pytorch --image-size 512 --network-capacity {whatever you used}`. I'll make this more seamless later today by storing these settings in a dot file

**Comment by lucidrains** [comment]
@albusdemens I just pushed a new version of the library. From now on, the network settings during training are stored and on generation it will auto instantiate the GAN correctly. You may retroactively fix your problem if you know the image size and network capacity you trained with, and continue training a bit further until the next checkpoint, in which case the problem will correct itself.

**Comment by albusdemens** [comment]
Thanks heaps! Everything runs fine now.
