### ISSUE TITLE
Expected run time with 2 GPUs

### ISSUE THREAD

**Issue by merttoka** [lucidrains/stylegan2-pytorch#151]
Thanks for the awesome repo. 

I am helping a faculty member so he can train a model with his photographs and generate images based on those. When we start the training using the `--multi-gpus` argument, I see that it initializes two processes (assuming for each GPU). However, we are not sure how long the training is expected to take with 2 RTX 2080s. Our first run took about 45 hours and it only reached 9%. Is this an expected duration or do you think there is something wrong with our current setup?

Best,
Mert.

**Comment by lucidrains** [comment]
@merttoka Hello Mert! You can get a rough idea here https://github.com/NVlabs/stylegan2#preparing-datasets This repository isn't as optimized as the official tensorflow version, so it may be even slower than that!

**Comment by lucidrains** [comment]
45 hours is nothing when it comes to training high resolution GANs!

**Comment by merttoka** [comment]
Got it, thanks. I will pay more attention to preparing the datasets and train again.

**Comment by lucidrains** [comment]
@merttoka at higher resolutions, you would need to extend your training steps `--num-train-steps` to be much greater!
