### ISSUE TITLE
Error(s) in loading state_dict for StyleGAN2:

### ISSUE THREAD

**Issue by terriblewitlogic** [lucidrains/stylegan2-pytorch#156]
I see this error has happened before when the repo has been updated. 
I'm using Google Colab, so it's downloading the new version every time I start a new session. 
I'm able to get some  checkpoints to load, but most fail with this error.
I'm losing progress and it's eating up a ton of time trying different checkpoints until one loads.
Is there something else I can try?

**Comment by terriblewitlogic** [comment]
I tried going back one version - !pip install 'stylegan2_pytorch==1.2.3'
same error

**Comment by lucidrains** [comment]
@terriblewitlogic ahh, you'll have to step through the versions until you hit the one that works, unfortunately. i'll start saving the version with the model soon!

**Comment by terriblewitlogic** [comment]
the checkpoints I'm loading are from last night - any idea which version numbers I should be trying, no luck so far?

**Comment by terriblewitlogic** [comment]
I suspect this isn't related to the version. I've had the problem every day this week and sometimes know good checkpoints have the problem. I suspect that it's related to corruption from copying the files. The checkpoints restore fine in their original instance, but if I move them to my google drive and back or download and upload them to my local system, they often fail with this error.
