### ISSUE TITLE
Change from 16px dataset to 32px data set and increase resolution of model?

### ISSUE THREAD

**Issue by thekesslereffect** [lucidrains/stylegan2-pytorch#158]
In my head it makes sense to start with a super low resolution dataset to train on and then increase the resolution of the dataset and output resolution as the model gets better. Is this possible to do? Or do I have to stick with one resolution the entire time?

data=16px trainingresolution=16px -> data=32px trainingresolution=32px without starting over from scratch.

**Comment by lucidrains** [comment]
It isn't possible sadly :( not with stylegan v2

**Comment by thekesslereffect** [comment]
Aww darn. Welp starting over then. Thanks for the info!
