### ISSUE TITLE
Save previews as often as models

### ISSUE THREAD

**Issue by tannisroot** [lucidrains/stylegan2-pytorch#159]
Hi, I've noticed that if I define the regularity with which the models are saved using `--save_every` option, it doesn't affect how often the previews are saved, they still generated only every 1K steps. 
Would it be possible to use the value from that option to determine how often previews are created as well?

**Comment by lucidrains** [comment]
@tannisroot sure! https://github.com/lucidrains/stylegan2-pytorch/releases/tag/1.2.6
