### ISSUE TITLE
Memory error during install

### ISSUE THREAD

**Issue by flumu** [lucidrains/stylegan2-pytorch#16]
Hello 
if i want to install stylegan2 the installation always fills up the RAM and swap file after almost downloading the second file
"https://files.pythonhosted.org/packages/46/ca/306bb933a68b888ab1c20ede0342506b85857635f04fb55a56e53065579b/torch-1.4.0-cp27-cp27mu-manylinux1_x86_64.whl"

at 99 % I can see that the installation process fills up the RAM to 90 % and the swap to 80 %.

After hours being in this state, it gave me a memory error.
Sadly I did not copy the code (It was late and I was frustrated ;) ) I will reply it if necessary.

But my first thought was:
Is there a maybe minimum memory requirement for stylegen2?

My system is a Xubuntu 19.04, I have 4 GB of RAM and 8 GB of Swap.
Maybe that is too less and that's why it crashes

**Comment by lucidrains** [comment]
Oh no, it seems related to the installation of the main deep learning package, pytorch, than it is about my package. I found https://discuss.pytorch.org/t/out-of-memory-error-with-pytorch-installation/18734 . Could you try with the `--no-cache-dir` flag on installing with pip?

**Comment by flumu** [comment]
Yes that really worked. It still filled up the memory to the moon but in the end (After like 30 min waiting) it worked.Thank you for your fast reply!

**Comment by lucidrains** [comment]
no problem! have fun experiencing this phenomenon, "disentanglement" :)
