### ISSUE TITLE
How can I debug this project in pycharm(or some other IDE)?

### ISSUE THREAD

**Issue by UESTCrookieLI** [lucidrains/stylegan2-pytorch#161]
I used to debug projects which using command like 'python train.py' in pycharm.
Now this repo using command  'stylegan2_pytorch --data /path/to/images' 
So I do not debug this preject.
could you tell me how you debug this prejects?
thanks!

**Comment by hhc1997** [comment]
Hello,  I have missed the same issue. How do you solve this?
