### ISSUE TITLE
Confusing Code

### ISSUE THREAD

**Issue by haqishen** [lucidrains/stylegan2-pytorch#17]
https://github.com/lucidrains/stylegan2-pytorch/blob/8e4ebf8a7bf92f1d6c2548d4ead5cc834f9da63d/stylegan2_pytorch/stylegan2_pytorch.py#L513-L515

I didn't understand what happens here, is `style, noise = inputs[i] ` really needed?

**Comment by lucidrains** [comment]
@haqishen nice catch! I was trying to make the training more memory efficient, but forgot to revert my efforts. I'll clean it up later tonight! Ideally I wanted the generator to learn on the exact style and noise vectors that the discriminator trained on above, so I will probably keep that line around

**Comment by lucidrains** [comment]
@haqishen https://github.com/lucidrains/stylegan2-pytorch/commit/0b061d4552333a841cf14f0008d16068ee268a06 fixed!
