### ISSUE TITLE
Generate 1000s of Images

### ISSUE THREAD

**Issue by pheonixhar** [lucidrains/stylegan2-pytorch#176]
After training the model, how do I generate large number of images ?
I can use --generate but that generates one image at a time.

**Comment by lucidrains** [comment]
@pheonixhar I added a `--num-generate {int}` flag in the latest version, let me know if that works for you!

**Comment by pheonixhar** [comment]
Thanks @lucidrains, it worked.I am closing the issue.

**Comment by luyan0422** [comment]
failed
