### ISSUE TITLE
Jetson Nano / minimal requirements?

### ISSUE THREAD

**Issue by sjoerdju** [lucidrains/stylegan2-pytorch#18]
Hi there,

I bought a Jetson Nano for experimentation and an arts project and would like to run the script. After some fiddling I managed to install the script, but I get out of memory errors. Is there some minimum necessary RAM (4GB on the nano), or should a big swap suffice?

Thnx!

**Comment by rhoen** [comment]
When I was first running the script I was seeing out of memory errors too. I was able to get it running by reducing the image size. I’ve read online elsewhere that reducing batch size can sometimes help, but I think the default batch size is already pretty low at 3, and reducing it to 1 didn’t help me. For reference my gpu has 2 gigs of ram and I was able to get running with an image size of 64.

**Comment by lucidrains** [comment]
@sjoerdju You can also adjust the network capacity! `--network-capacity {num}` I think the default is somewhere around 16

**Comment by lucidrains** [comment]
@sjoerdju I'll add some documentation around this soon, I wasn't expecting this much interest

**Comment by sjoerdju** [comment]
Thnx for both of your comments! I'll try and let you know if it worked.

Documentation would be fantastic. Let me know if I can be of any help. I'm rather green in this field so a script like this is great for trial and error :)

**Comment by lucidrains** [comment]
@sjoerdju yes! perhaps once you get it working, just let me know what would have helped, and I'll add it to the readme. I should definitely document the network capacity (which defines the capacity of the neural network) somewhere

**Comment by lucidrains** [comment]
added some instructions in the Readme here https://github.com/lucidrains/stylegan2-pytorch/commit/ef9474f1e64b1cf35d5445b97af1b8c2aab51fe0
