### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by foobar8675** [lucidrains/stylegan2-pytorch#181]
first, thanks for this awesome project. I'm not following something and was hoping you could help?

what is the difference between self.S and self.SE, self.G and self.GE?
https://github.com/lucidrains/stylegan2-pytorch/blob/master/stylegan2_pytorch/stylegan2_pytorch.py#L625

**Comment by lucidrains** [comment]
@foobar8675 Hi Matthew! So S and G stands for the mapping network and the generator, respectively. E stands for exponential moving average. It's been shown that keeping an exponential moving average of the generator (mapping + generator) yields better quality generations

**Comment by foobar8675** [comment]
awesome. thanks1
