### ISSUE TITLE
another code question regarding disc_loss and divergence

### ISSUE THREAD

**Issue by foobar8675** [lucidrains/stylegan2-pytorch#188]
I'm wondering why there are 2 variables, `disc_loss` and `divergence`

https://github.com/lucidrains/stylegan2-pytorch/blob/master/stylegan2_pytorch/stylegan2_pytorch.py#L948

since fq and gradient penalty are only applied to `disc_loss` and not `divergence` but divergence is used for logging? why not use `disc_loss` for logging and remove `divergence`?

**Comment by lucidrains** [comment]
@foobar8675 Hey Matthew! The reason is because I want to be able to display the user the separate auxiliary losses

If they were all summed together, the user won't be able to see each contribution

**Comment by foobar8675** [comment]
ah, got it. thanks :)
