### ISSUE TITLE
  Is the code not  trained from low resolution to high resolution?

### ISSUE THREAD

**Issue by Young1403** [lucidrains/stylegan2-pytorch#19]

**Comment by lucidrains** [comment]
@Young1403 no longer lol. That was so last year. The new version no longer uses progressive growing, which fixes a number of visual artifacts

**Comment by lucidrains** [comment]
It makes everything a lot simpler too, as you can see

**Comment by Young1403** [comment]
@lucidrains Well, thanks for your reply!
