### ISSUE TITLE
gpl license = evil - https://medium.com/@jcastromail/gpl-license-is-evil-2f71622399d6

### ISSUE THREAD

**Issue by johndpope** [lucidrains/stylegan2-pytorch#195]
https://medium.com/@jcastromail/gpl-license-is-evil-2f71622399d6

given that the guys at nvidia labs are moving to use pytorch from tensorflow - understand that due to GPL license - this codebase and any derivative work from it is of no use to them. It's a total no go zone not even as code reference. It all has to be rewritten from ground up.
https://github.com/NVlabs/stylegan2-ada/issues/32

**Comment by lucidrains** [comment]
@johndpope I only did GPL because the original repository is GPL. isn't that what I am required to do since my code is based off of Nvidia's?

**Comment by johndpope** [comment]
you basically derived this code from manicman's tensorflow2 port - which was MIT. stylegan / 2 / ada is all MIT.
https://github.com/NVlabs/stylegan2-ada/blob/main/LICENSE.txt

There is some code some where that had a GPL reference but I think that's a plugin or some sort. have to find it.

**Comment by lucidrains** [comment]
@johndpope yea, but the main Stylegan architecture is Nvidia's? so dont I need some sort of more restrictive license? or do I not understand licenses?

**Comment by lucidrains** [comment]
it happened with https://github.com/lucidrains/lightweight-gan as well, the author emailed me asking me to make it GPL

**Comment by johndpope** [comment]
The author can request that - it has ramifications - he doesn't own that license - it's yours / it's your code. If some business wants to use your code commercially they need to get the permission from you and pay you. He is not entitled to royalties from that transaction.  If another coder independently (NOT DERIVED from yours) creates an MIT version  from lightweight -gan whitepaper - then people can shop around and choose which code base to use. He can't enforce this. It's a form of barrier of trade. But here - above - the stylegan2 architecture was given as MIT to the world by NVIDIA. Why? People have to use cuda to get anywhere with that code. The stylegan2 code is MIT / sublicensable. It get's blurry with datasets - MS Coco / etc - where there's some IP / creative non commons where by you could be releasing / charging for models / datasets that you're not given the right to do. for this vanilla implementation of porting stylegan2 - pytorch / developers will need to yield to this MIT version
https://github.com/rosinality/stylegan2-pytorch

**Comment by lucidrains** [comment]
your linked repo doesn't even have a license

sure I agree, I'm just trying to avoid trouble. so you are sure I can make this repo MIT without any ramifications?

**Comment by johndpope** [comment]
MIT - https://github.com/rosinality/stylegan2-pytorch/blob/master/LICENSE
you wont be able to chase people for money / royalties for commercializing your code. Nor would you be able to force people to open source their codebases / applications.That's a couple of ramifications. If people look at code - prior to MIT license update - then it falls under that older license.

**Comment by lucidrains** [comment]
@johndpope yea, neither of that is what I'm looking for

ok, making it MIT then!

**Comment by lucidrains** [comment]
https://github.com/lucidrains/stylegan2-pytorch/commit/666998c3d9f679613b1633f9e4e1db6f006690a1

**Comment by johndpope** [comment]
cool - might help nvidia labs.
