### ISSUE TITLE
problems with ModelLoader

### ISSUE THREAD

**Issue by cityCoder** [lucidrains/stylegan2-pytorch#197]
Hi,
It's a very nice implementation, thanks for sharing!
I tried to train a model with my own dataset, it works pretty well, and I am able to produce nice images with the command line. I want to move forward by producing images via coding. I tried ModelLoader as instructed and thought the model was loaded correctly as I saw 
> continuing from previous epoch - 62
> loading from version 1.5.6

However, the generated images are not correct,  here is an example:
![sample](https://user-images.githubusercontent.com/9147453/103450303-63472b00-4c82-11eb-9434-674724e7d40b.jpg)

The picture seems like being produced by a model with random parameters. Could you help me to resolve it?

**Comment by lucidrains** [comment]
Hello! Could you try the following code and see if it generates images at `./results/test.jpg` correctly?

```python
model = ModelLoader(...)
model.model.evaluate('test', 4)
```

**Comment by cityCoder** [comment]
Thanks for your reply!  These images are not correct. I also tried the exponential moving average version. It fails either.

**Comment by lucidrains** [comment]
@cityCoder hmm, but it works when you are training it? are you training with a specific project name? `--name {name}`

**Comment by cityCoder** [comment]
@lucidrains Yes, It works nicely during training and when I run 

> stylegan2_pytorch --generate

I did not train with a specific project name. My training images are of a different size (i.e. 400x400).

**Comment by lucidrains** [comment]
@cityCoder I found the bug! https://github.com/lucidrains/stylegan2-pytorch/commit/c91e5007a291b761b83de40b1426523327863b84

**Comment by lucidrains** [comment]
thank you for reporting this :D

**Comment by cityCoder** [comment]
Thank you!
