### ISSUE TITLE
Generate only 1 image

### ISSUE THREAD

**Issue by luchoster** [lucidrains/stylegan2-pytorch#20]
Would it be possible to generate only 1 image? similar to what thispersondoesnotexist.com does it?

I'm still training atm, but I figured the end result of the generation of images, is 8x8 collage of images, am I right?

**Comment by lucidrains** [comment]
@luchoster yea! i had no idea somebody would get this far! I can offer another flag? `--num-image-tiles` ? Or how do you think it should be named?

**Comment by luchoster** [comment]
I think that flag name makes sense, that'd be awesome!!!

I'm 47% into the training, so it'd be awesome to have that option. Also, how long does it take to generate an/the images? I would love to build a clone of thispersondoesnotexist :)

**Comment by lucidrains** [comment]
@luchoster if you have a GPU, a single image would be less than 100ms. It'll be very fast! What are you training it on? Is it learning?

**Comment by luchoster** [comment]
ooo that's goood!
I have a windows machine for this.

Here are some pictures of the training.

![4-mr](https://user-images.githubusercontent.com/694367/74961372-d3c6bf80-53c2-11ea-8bcc-eccd28b23992.jpg)
![20-mr](https://user-images.githubusercontent.com/694367/74961379-d6c1b000-53c2-11ea-8d92-d10f50acc926.jpg)
![40-mr](https://user-images.githubusercontent.com/694367/74961389-d9bca080-53c2-11ea-9e8d-e789c0b010dc.jpg)
![41-mr](https://user-images.githubusercontent.com/694367/74961395-dc1efa80-53c2-11ea-825c-f4c738235b76.jpg)
![46-mr](https://user-images.githubusercontent.com/694367/74961401-dde8be00-53c2-11ea-8c39-73258258ab69.jpg)
![47-mr](https://user-images.githubusercontent.com/694367/74961408-e04b1800-53c2-11ea-8f9c-2b839a92b1ac.jpg)

**Comment by luchoster** [comment]
the last 2 are the most recent ones, 46 and 47 %. As you can see, it started to generate nice faces and in the last 2, started to get weird again haha

**Comment by lucidrains** [comment]
@luchoster very cool! when the discriminator loss hits 0 consistently, `D: {num}` in the logs, the training is done, and you usually have to pick the generator just before it explodes

**Comment by luchoster** [comment]
oh that's good to know. I'll keep an eye on that.

**Comment by lucidrains** [comment]
@luchoster ok, I just updated the package with the new flag! just set it to 1 and you are all set

**Comment by luchoster** [comment]
you are awesome!!!!
Thank you! I'll keep you posted on the results :)

**Comment by lucidrains** [comment]
@luchoster please do!

**Comment by tjukanovt** [comment]
@lucidrains I am also trying to create only a single image as in the original issue, but can't seem to get this working. I am running command `stylegan2_pytorch --data /mydata/ --name mapproject --results_dir /myresults/ --models_dir /mymodels/ --num_image_tiles 1`

also tried with `--num_image_tiles 1` and modified all the `num_image_tiles = 8 ` values to 1 in the Python script, but nothing seems to change the outputs. 

Still I am not getting a single image, but a mosaic instead.
![7](https://user-images.githubusercontent.com/13899537/75956276-37231800-5ec0-11ea-8102-0c8b13438543.jpg)

**Comment by HeleenE** [comment]
Oeh I'm super interested in this new flag as well! Been training the software on a very small set of drawings, but with surprisingly good results. It would be nice to create some higher res versions. Now running the training again with the image- size 256 flag, going to take some time 😅 

I'm running it on Google Colab, but it hasn't been super stable. Sometimes it crashes right before the 10000 save. If I lower that number in the code would it also create more models?
`SAVE_EVERY = 10000 `
