### ISSUE TITLE
Different Image Sizes

### ISSUE THREAD

**Issue by Thierryonre** [lucidrains/stylegan2-pytorch#203]
What would happen if I tried to train this on a dataset that had images which had different widths and heights?
Would it still be able to train and generate good quality images?

**Comment by therealjjj77** [comment]
Doubt it. Due to the way Conv NNs work, you're likely to get an error. Just run a Python script to crop and resize your images or use some program to do it.

**Comment by Dok11** [comment]
I use script for this purpose before start training:

```
import os
from PIL import Image
import pkbar


source_path = './images/different-size'
target_path = './images/result'
size = 1024

files = os.listdir(source_path)
pbar = pkbar.Pbar(name='files', target=len(files))

i = 0
for file in files:
    if file.endswith('.jpg'):
        image = Image.open(os.path.join(source_path, file))
        new_image = image.resize((size, size))
        new_image.save(os.path.join(target_path, file))

    i += 1

    if i % 10:
        pbar.update(i)
```
