### ISSUE TITLE
Trouble finding out command-line arguments

### ISSUE THREAD

**Issue by woctezuma** [lucidrains/stylegan2-pytorch#22]
I see in the README that there are command-line arguments, such as `image-size`, and I would like to find out the exhaustive list of possible command-line arguments.

However, I have a bit of trouble understanding the code in `stylegan2_pytorch.py`. I don't see any `main()` function. I am familiar with Python, but it seems that you are using it in a way which I don't know about, with that binary file in `bin/`.

Could you point out where I should look at?

**Comment by mulka** [comment]
The file in bin/ is a Python file. At the bottom, it looks like it is using the fire package to call the train_from_folder function in that same file. I'm guessing that using "--help" with the command will give you a list of the options, but you could also look at the arguments to the train_from_folder function as well. Let me know if that helps.

**Comment by woctezuma** [comment]
> The file in bin/ is a Python file.

Thank you! This makes things clearer!

I did not know that the file in bin was a text file: I assumed it might be some pre-compiled binary file)

**Comment by woctezuma** [comment]
So, [Python Fire](https://github.com/google/python-fire) is a library to generate command-line interfaces.

The list of command-line arguments, and their default values, are given by the `train_from_folder()` function, as you mentioned:

```python
def train_from_folder(
    data = './data',
    results_dir = './results',
    models_dir = './models',
    name = 'default',
    new = False,
    load_from = -1,
    image_size = 128,
    network_capacity = 16,
    batch_size = 3,
    gradient_accumulate_every = 5,
    num_train_steps = 100000,
    learning_rate = 2e-4,
    num_workers =  None,
    generate = False,
    num_image_tiles = 8
):
    # [...]
```
