### ISSUE TITLE
Expected iteration time

### ISSUE THREAD

**Issue by MartinKing01** [lucidrains/stylegan2-pytorch#231]
Hi!

First of all, thank you for this amazing project.

I just want to ask you the expected iteration time for a GTX 1060 3 GB GPU (I know its not the best for this kind of job). 
It's 4sec/it, but other people seems to get the same time for kimg. Does it mean that my time is 1000 times slower than others, or I just can't understand this stuff? :) 

Thank you in advance

**Comment by baibizhe** [comment]
I trained on V100. I remembered it is 7sec/it
