### ISSUE TITLE
`filter2D` will be renamed to `filter2d`

### ISSUE THREAD

**Issue by Rafat97** [lucidrains/stylegan2-pytorch#236]
# Problem
filter2D will be renamed to filter2d

# What's problem I face? 
I got this Warning
```python
/usr/local/lib/python3.7/dist-packages/kornia/filters/__tmp__.py:11: DeprecationWarning: `filter2D` will be renamed to `filter2d` in the future versions. Please use `filter2d` instead.
  category=DeprecationWarning,
```

For this warning I can't see the output result. You can see this into given screenshots-
![image](https://user-images.githubusercontent.com/21246862/121786280-b4b7f680-cbe0-11eb-8ae8-6fe83f98c663.png)

# My solution :
Installing lower version of `kornia` use -
!pip install kornia==0.5.3

**Comment by lucidrains** [comment]
@Rafat97 Hi! Do you want to try 1.8.3 and let me know if that removes the warning?

**Comment by Rafat97** [comment]
@lucidrains I will try this `v1.8.3`.  `filter2D` warning was removed. 

But another warning is appear. That  is - 
```python
/usr/local/lib/python3.7/dist-packages/kornia/augmentation/augmentation.py:1833: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
```

Thank you.
