### ISSUE TITLE
Cannot run on windows

### ISSUE THREAD

**Issue by dave7895** [lucidrains/stylegan2-pytorch#25]
I always get the error message 
````
'stylegan2_pytorch' is not recognized as an internal or external command,
operable program or batch file.
````
although it definitely is in my path.

**Comment by lucidrains** [comment]
@dave7895 Could you share how you installed it? Could you retry under a new virtual environment?

**Comment by dave7895** [comment]
I created a new virtual environment with conda. Then ran the commands to install stylegan2_pytorch via pip. Tried to run it but can't find any approach to get it to run.

**Comment by lucidrains** [comment]
@dave7895 Could you try with a new environment, but this time, run `conda install pip`, and then use the `pip` under that environment to install `stylegan2_pytorch`?

**Comment by dave7895** [comment]
am I maybe missing a step?
1.new conda environment
2.add pip, pytorch, torchvision and stylegan2_pytorch
3. then continue in the console or in python?

**Comment by lucidrains** [comment]
@dave7895 no, i don't think so, if you do it in that order, and if you use the `pip` installed from conda

**Comment by dave7895** [comment]
working on it right now. shell console or python console?

**Comment by nicholasc** [comment]
I'm having the same issue. @dave7895 did you get it to work by any chance?

**Comment by nicholasc** [comment]
I went straight to `C:\Users\[MyUser]\Miniconda3\Scripts` and ran it with `python stylegan2_pytorch`. Not pretty but worked.

**Comment by chiften-p** [comment]
i'm having the same issue, any one ?

**Comment by dave7895** [comment]
@chiften-p I do it just about as nicolasc does it.
```
python C:\users\[username]\miniconda3\envs\style_gan\scripts\stylegan2_pytorch --data C:\Users\[username]\Style_Gan\Chrome
```
is my command with a few additional tweaks to get it to run memory wise

**Comment by dave7895** [comment]
@nicholasc I'm using your idea now and at least it works.

**Comment by chiften-p** [comment]
there is a file in bin folder
[https://github.com/lucidrains/stylegan2-pytorch/blob/master/bin/stylegan2_pytorch](url)
i use this and it works well.

**Comment by dave7895** [comment]
that's what I said :). only with the file from the pip module and not the cloned git-project, it's the same file
