### ISSUE TITLE
How to make interpolation from specific model

### ISSUE THREAD

**Issue by ItCameFr0mMars** [lucidrains/stylegan2-pytorch#256]
I want to make an latent space interpolation from the latest trained model. here is the command I am using
`!stylegan2_pytorch --generate-interpolation --interpolation-num-steps 700`
I have tried to use the option 
`--models_dir` 
but that does not seem to work. 
Any help will be appreciated.

**Comment by Aquassaut** [comment]
`--models_dir`/`--models-dir` seems to work for me

**Comment by ItCameFr0mMars** [comment]
do you replace the second --models-dir with the path? do you keep the "/"?

**Comment by ItCameFr0mMars** [comment]
nvm, i fixed using
```!stylegan2_pytorch --generate-interpolation --interpolation-num-steps 50 --models_dir (path) --name (name of model folder)```
