### ISSUE TITLE
Possible to safe more often?

### ISSUE THREAD

**Issue by HeleenE** [lucidrains/stylegan2-pytorch#27]
Loving this repo, thank you! 

I'm running it on Google Colab, but it hasn't been super stable. Sometimes it crashes right before the 10000 save. If I lower that number in the code would it also create more models?
`SAVE_EVERY = 10000 `

**Comment by lucidrains** [comment]
@HeleenE Hi Heleen! I've made it so you can specify the frequency at which you save the model by exposing the command line argument `--save-every` (which I've lowered it to 1000 by default). Let me know if that works for you!

**Comment by HeleenE** [comment]
@lucidrains Thank you, that's wonderful! I was also wondering which`--image-size` flag you've used for thispersondoesnotexist?

**Comment by lucidrains** [comment]
thispersondoesnotexist was actually trained by Nvidia using an image size of 1024x1024. It will probably be difficult to train at that resolution with this repository, but you can certainly try! I would recommend using the official repository if you do and start off using one of their pre-trained models to transfer learn.

**Comment by HeleenE** [comment]
Thank you! I'm not sure if my deadline will allow for that, but I'll look into it. Getting pretty impressive results with the `--image-size 256` flag. Hope to train the model on the `--image-size 512` flag, but Google Colab doesn't seem to have enough ram for that. I'll try to play around with the batch, etc flags to see if I can get it up and running.

**Comment by dancrew32** [comment]
@HeleenE sorry to bother, but I'm curious, did you find a cost effective solution for getting to >=512?
I wish I saw your comment earlier as I tried a bunch of permutations unsuccessfully here https://github.com/lucidrains/stylegan2-pytorch/issues/35#issuecomment-619445261 Thanks for your time.
