### ISSUE TITLE
Bug: random_hflip function

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/stylegan2-pytorch#273]
With ref to: https://github.com/lucidrains/stylegan2-pytorch/blob/master/stylegan2_pytorch/stylegan2_pytorch.py#L389-L392
```
def random_hflip(tensor, prob):
    if prob > random():
        return tensor
    return torch.flip(tensor, dims=(3,))
```

Should prob be augment probability or non-augment probability? If we set prob=1.0, then we do NOT do horizontal flip 100% of the time.

**Comment by lucidrains** [comment]
@xiankgx oh shoot, yes you are right :pray: https://github.com/lucidrains/stylegan2-pytorch/commit/0588213d4e552095905873a24f577007c40c1667
