### ISSUE TITLE
Training not using much of GPU? Is this normal?

### ISSUE THREAD

**Issue by swayamz** [lucidrains/stylegan2-pytorch#28]
On my windows machine, Training appears to have high CPU usage however my GPU usage tends to be around 1%. Is this normal behavior?

**Comment by lucidrains** [comment]
@swayamz it should be using a fair amount of your GPU memory, what does `nvidia-smi` say?

**Comment by WoshiBoluo** [comment]
![image](https://user-images.githubusercontent.com/52227723/110273061-b2089c80-8006-11eb-9741-0df70a3e5a14.png)
It seems not use GPU，so that too slow. If any command to solve? Thank you~~
