### ISSUE TITLE
Recommended specs for training?

### ISSUE THREAD

**Issue by iboates** [lucidrains/stylegan2-pytorch#3]
I asked this in my previous issue but because it was closed maybe it was not seen.

What kind of specs do you recommend for training this model? I was trying it on Google Colab but it was running extremely slowly (30s for a single iteration in a folder with 5 images), however this does not surprise me since Google Colab is by no means an industrial solution. If I want to scale this up to something significant, what would you recommend for minimum specifications?

**Comment by iboates** [comment]
Actually it looks like I made a mistake, I was not connected to a GPU runtime instance. It is significantly faster now (1.4s per iteration). Regardless, I would still like to know some more details about how you trained the model seen at thispersondoesnotexist.com. How many images did you use, and how many of which model GPU did you use?

Thanks

**Comment by lucidrains** [comment]
Hi @iboates ! What size images are you trying to train?

**Comment by lucidrains** [comment]
The sample images I've trained are only 256x256, and it took me about 2-3 days on my lone GTX 2080 Ti. The repository is optimized for simplicity and convenience, and not really memory efficient (yet). For 1024x1024, I would still recommend the original StyleGan2 repository, preferably trained with transfer learning off one of the pretrained models. Let me know if you have any further questions!
