### ISSUE TITLE
Saving of models

### ISSUE THREAD

**Issue by dave7895** [lucidrains/stylegan2-pytorch#37]
Am I correct in the assumption that the save models get updated all the time and not just when saving and this save is just the creation of a permanent and non-changing model? Or is everything happening from the start to the first save point, 1000 by default I think, gone to waste if I were to stop it before reaching this mark?

**Comment by lucidrains** [comment]
@dave7895 models are periodically saved at intervals of 1k iterations, and you can find it under `./models/{project name}`. they should be never overwritten, and you can even go back in time and load previous models along the way with `--load-from {checkpoint num}`

**Comment by dave7895** [comment]
I understand. Sorry for my possibly badly formulated question. I meant: If I train 990 iterations and then interrupt the script, are all the 990 iterations wasted or are they in the most recent model and if I continue there are basically 1990 iterations in this checkpoint added?

**Comment by lucidrains** [comment]
@dave7895 ahh, they are wasted, it's too expensive to save every iteration. however, you can change the frequency at which it saves with a `--save-every` flag

**Comment by dave7895** [comment]
Yeah, okay I can understand this. Did this change with a more recent release as I hadn't updated my package and so the `--save-every` flag did not work. But I did not know this and so I trained it about 15k iterations but always interrupted before the checkpoint as I did not know it was at 10k and not 1k. These are the ones named automatically 0.jpg, so the ones before the first checkpoint.
![0-ema](https://user-images.githubusercontent.com/56267906/78337741-c25ffe00-7591-11ea-9b8b-3715ba3c8206.jpg)
![0](https://user-images.githubusercontent.com/56267906/78337746-c4c25800-7591-11ea-839b-0b2806fbdc5b.jpg)
![0-mr](https://user-images.githubusercontent.com/56267906/78337749-c5f38500-7591-11ea-842f-66b6cf09da77.jpg)

That's why I am confused because I parallely train on colab and there the ones from before the 1st checkpoint look like this:
![0](https://user-images.githubusercontent.com/56267906/78337849-f76c5080-7591-11ea-8c8a-a644902044a8.jpg)
![0-ema](https://user-images.githubusercontent.com/56267906/78337865-fe935e80-7591-11ea-8c03-6ab61dbb62d2.jpg)
![0-mr](https://user-images.githubusercontent.com/56267906/78337869-ffc48b80-7591-11ea-9f7f-108be4b59692.jpg)

**Comment by lucidrains** [comment]
oh sorry I think I misunderstood. If you run the same command with the same project name (or leave at default), it will pick up where you left off

**Comment by lucidrains** [comment]
Oh and yup, save-every was added in recent updates!

**Comment by dave7895** [comment]
Thanks for the clarification. Where does this get saved then?

**Comment by lucidrains** [comment]
@dave7895 it's saved to the `./models` folder where you executed the command

**Comment by dave7895** [comment]
Ok so just updating and then duplicating with only one evolving at the 1k mark? Is this happening when the images are updated?

**Comment by lucidrains** [comment]
@dave7895 yup! it happens every time the images are updated

**Comment by dave7895** [comment]
Ok. Thanks for your time.
