### ISSUE TITLE
Features of latest update

### ISSUE THREAD

**Issue by dave7895** [lucidrains/stylegan2-pytorch#38]
What do the newly exposed features do? For example the psi-trunc?

**Comment by lucidrains** [comment]
@dave7895 this feature is actually a hack that people in the GAN field make the generated images look better. what they do is they estimate the average latent vector, and make sure that the random latent vector you sample does not stray too far from the average. `--trunc-psi` ranges from 0 to 1, and denotes that distance.

**Comment by dave7895** [comment]
I am not really experienced with the whole field, rather just starting out, so I do not really know what a latent vector is. Would just a very general short description or explanation be possible if it is not too much?

**Comment by dave7895** [comment]
These numbers come from the nodes of the neural net?

**Comment by lucidrains** [comment]
@dave7895 you pass this latent vector into the net, you get to choose them!

**Comment by dave7895** [comment]
Is it so that the network chooses one of the 512 and with psi-trunc you make the space of choosing for centered and try to remove outliers?

**Comment by lucidrains** [comment]
@dave7895 yes, actually I randomly sample 512 numbers (`z`), and the outliers are removed once they are transformer to `w` (style vector)

**Comment by lucidrains** [comment]
@dave7895 each individual image actually comes from a specific set of 512 numbers. i choose them randomly, but you can set those numbers yourself

**Comment by dave7895** [comment]
So it would be possible to use the exact same set of numbers on different models and then watch the about the same face get generated by different generations?

**Comment by dave7895** [comment]
That I can understand. Just like brains being different between siblings for example. But how is it with the same network a thousand iterations later?

**Comment by lucidrains** [comment]
@dave7895 ohh, what do you mean? do you mean how is the face for the same latent vector of the same network trained for 1k iterations?

**Comment by dave7895** [comment]
The actual question was if the latent space, which defines the possible latent vector due to its dimensions if I understood correctly, changes during training. If it does not change then you could feed the same numbers each time at least once, and you could see one of the faces evolving as the network evolves.

**Comment by lucidrains** [comment]
@dave7895 oh yes, many people do that with GANs already! [https://pythonawesome.com/content/images/2019/08/celeba_dragan.gif](example)

**Comment by dave7895** [comment]
oh, that looks nice. Thank you for the insights.
