### ISSUE TITLE
Error information

### ISSUE THREAD

**Issue by dave7895** [lucidrains/stylegan2-pytorch#39]
I just got this Error:
```
return self.lambd(img)
  File "/usr/local/lib/python3.6/dist-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 114, in expand_to_rgb
    return tensor.expand(3, -1, -1)
RuntimeError: The expanded size of the tensor (3) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [3, -1, -1].  Tensor sizes: [2, 128, 128]
```
I suspect it comes from a picture that does not have 3 channels but 2, from the last line. But that seems strange to me so I wanted to ask what you believe is causing this.

**Comment by dave7895** [comment]
I believe I could resolve it by hand. Somehow there were greyscale pngs in the dataset. So they had 2 channels, like greyscale jpg plus alpha. Really weird

**Comment by nikmel2803** [comment]
Hi, @lucidrains 
I have the same error with my dataset, but I don't understand why it arises. 
I couldn’t find any information about what the dataset should be (image's sizes, colors, extensions). What do you think about this? You can find my dataset [here](https://1drv.ms/u/s!AqFroX55eWupnLduWDhyEsDX4ITioQ?e=azLzZU).
Thanks.

**Comment by dave7895** [comment]
@nikmel2803 the preprocessing pipeline can handle most picture formats. it can take black and white pictures(1 channel), normal RGB JPGs(3 channels) and pngs(RGB plus alpha, 4 channels). it can't handle black and white pngs with two channels because it was not coded in due to its rarity. can't look at your dataset right, but what are you trying to do?

**Comment by nikmel2803** [comment]
I needed to parse photos from [this site](https://ru.openlist.wiki/Категория:Фотографии) and train the neural network to generate similar photos (it is graduate work :D)
I'll try to check is there any images with only two channels in my dataset.
BTW, in my dataset there are many images with different sizes. Can there be problems because of this?

**Comment by dave7895** [comment]
I think it won't be a problem, but I do not know what happens when there are pictures smaller then the passed size. You should know that all pictures are made to fit squares with width equal to 2^x. #44, here is some more info on the way images are processed before being put into the neural net.

**Comment by nikmel2803** [comment]
Do I need to set size? When it is necessary?

**Comment by nikmel2803** [comment]
I've converted all images to RGB and it fixed the error. Thanks)
I'll wait for the results of the work
