### ISSUE TITLE
Will training pick up where it left off?

### ISSUE THREAD

**Issue by iboates** [lucidrains/stylegan2-pytorch#4]
I'm using Google Colab and from what I understand, VMs are recycled after something like 10 hours of inactivity. But by my calculations I'm going to need at least 30. If I save the content of the "models/default" folder, will it pick back up again where it started rather than starting again?

**Comment by lucidrains** [comment]
@iboates so Colab is tricky. the best thing to do is to pay for an upgraded version of Google Drive, mount that, and periodically save your model there. Colab cuts you off if you show inactivity within the hour, or if you hit the 12 hour mark in the day. It's very stressful to keep it running (trust me I did it for half a year lol)

**Comment by lucidrains** [comment]
@iboates but to answer your question, if you do not change the settings, and keep the project name the same, and the models can be found, it will automatically resume from the last checkpoint

**Comment by iboates** [comment]
Alright thanks. In the meantime I will just backup the files manually and re-upload them to the new VM when i start again.

**Comment by lucidrains** [comment]
ok! let me know if you run into any other issues
