### ISSUE TITLE
Question regarding transparent images

### ISSUE THREAD

**Issue by NickAcPT** [lucidrains/stylegan2-pytorch#43]
Is it possible to use this project to generate images with transparency?

**Comment by lucidrains** [comment]
it should be possible! do you have a good dataset?

**Comment by NickAcPT** [comment]
I have a dataset with 400k 64x64 images with transparency. It is 700 mb I think

The problem is that I've been training StyleGAN with them ready. Guess I'll need to restart.

**Comment by lucidrains** [comment]
Could you send me a small subset (like 100 samples) of your dataset? I'm thinking perhaps with a flag like `--with-transparency`, and images will be stored as PNGs

**Comment by NickAcPT** [comment]
Sorry for the huge delay.
[Here](https://github.com/lucidrains/stylegan2-pytorch/files/4472068/skins.zip) is a small subset of my dataset with 100 files.

Also, I'll have to restart training and scrap my trained model, right?

**Comment by lucidrains** [comment]
@NickAcPT Stylegan1 isn't too bad! Why not keep training with the old model?

**Comment by NickAcPT** [comment]
What about transparency then?

**Comment by lucidrains** [comment]
@NickAcPT Oh I see, I thought you meant the official repo. Ok, will add!

**Comment by lucidrains** [comment]
@NickAcPT  here you go! https://github.com/lucidrains/stylegan2-pytorch/commit/a86eef2cfcacdfe96a9095d6ad0a00f20b77242f

**Comment by NickAcPT** [comment]
Thanks a lot!
Regarding the already trained set, the best is to retrain from scratch, right?

**Comment by lucidrains** [comment]
@NickAcPT yes! you will have to restart!

**Comment by NickAcPT** [comment]
Once again, thanks a lot!

**Comment by vijishmadhavan** [comment]
@lucidrains  Why while training only one image is showing?
![download (19)](https://user-images.githubusercontent.com/53169213/200437287-cfc26d29-9bae-4961-9920-383a47813450.png)
