### ISSUE TITLE
Resizing of photos

### ISSUE THREAD

**Issue by dave7895** [lucidrains/stylegan2-pytorch#44]
What happens to non-square photos? Are they cut off at the sides where they are longer, are they resized without respect to aspect ratio or is it conserved by adding black/white bars?

**Comment by dancrew32** [comment]
Think this is the image augmentation part of the pipeline:
https://github.com/lucidrains/stylegan2-pytorch/blob/master/stylegan2_pytorch/stylegan2_pytorch.py#L132-L133

Should the resize take place before the center crop? This order seems like it might cause output distortion.

Anywho, it appears all images that are trained on are guaranteed to be squares of your `--image_size` command line argument.

**Comment by dave7895** [comment]
Thanks for the lines in the code. I think understand now what is happening. First the image is downscaled with the shorter side being as long as the `--image_size` flag, then the center is cropped, so the sides, where the picture is longer, are dropped. Am I correct or seeing this wrong?

**Comment by lukemelas** [comment]
Yes, that is correct.

**Comment by dave7895** [comment]
Ok. Thanks for the clarification.
