### ISSUE TITLE
Training on a dataset containing over a million image

### ISSUE THREAD

**Issue by franclin** [lucidrains/stylegan2-pytorch#47]
Hi, 
 Do you think I can train it on a dataset with over a million image in color and whose image size is 28x28 pixels? Or you would suggest another GAN architecture?

**Comment by dancrew32** [comment]
Very interested in this as well. It seems like with more images you use, the better the output is, but it is unclear when there are diminishing returns. E.g. Would 2M images really be better than 1M?

@franclin, as you train on this dataset, please keep us updated! It would be extremely interesting to see how quickly you can get to a high quality GAN output. If you can prototype GANs faster by using really small images, getting a faster iteration time, that would be a interesting way to see if investing the time in a high resolution output >=1024px is worth it.

**Comment by lucidrains** [comment]
yea, this will work with a million images
