### ISSUE TITLE
Model collapse help

### ISSUE THREAD

**Issue by iboates** [lucidrains/stylegan2-pytorch#52]
I know that this is a very tricky problem but I am hoping that maybe you will have some advice. I have been trying to no avail to train a GAN which will generate maps, training on OpenStreetMap tiles.

I have just over 40k images of maps, focused loosely on small towns and villages in Germany. Soem example images are below:

![BB000000066](https://user-images.githubusercontent.com/13814358/80522165-6a4bca00-898c-11ea-86ba-ff74ca64e21e.png)
![BB000000146](https://user-images.githubusercontent.com/13814358/80522169-6cae2400-898c-11ea-8dfc-befdff9f4c20.png)
![BB000000217](https://user-images.githubusercontent.com/13814358/80522172-6ddf5100-898c-11ea-8cbe-5a2067989788.png)
![BB000000254](https://user-images.githubusercontent.com/13814358/80522175-6f107e00-898c-11ea-81a4-64e9bf1be61d.png)
![BB000000314](https://user-images.githubusercontent.com/13814358/80522180-7041ab00-898c-11ea-8f60-6a906e230d13.png)
![BB000000504](https://user-images.githubusercontent.com/13814358/80522193-76d02280-898c-11ea-9a57-e4d6d64dc647.png)
![BB000000676](https://user-images.githubusercontent.com/13814358/80522198-7899e600-898c-11ea-932f-d8c6003c2b56.png)
![BB000000775](https://user-images.githubusercontent.com/13814358/80522208-7d5e9a00-898c-11ea-93ae-5e5f756159a4.png)
![BB000000873](https://user-images.githubusercontent.com/13814358/80522237-88b1c580-898c-11ea-98ff-0b0af39ac49f.png)

However, it seems that no matter what I try, the model begins to collapse around 70k iterations. Originally I thought the problem was too much variation in the data, that's why I focused mainly on small towns, since they mostly have some buildings and streets nearby.

Here is an example of the progression of the model as it is collapsing:

Iteration 30k:
![30](https://user-images.githubusercontent.com/13814358/80522611-24dbcc80-898d-11ea-9a60-877ca556b366.jpg)

Iteration 40k:
![40](https://user-images.githubusercontent.com/13814358/80522619-2907ea00-898d-11ea-8264-7f0820c0bef7.jpg)

Iteration 50k:
![49](https://user-images.githubusercontent.com/13814358/80522635-2c9b7100-898d-11ea-8c94-f7f4ecac6819.jpg)

Iteration 60k:
![60](https://user-images.githubusercontent.com/13814358/80522647-31602500-898d-11ea-997b-f9084de320ca.jpg)

Iteration 70k:
![70](https://user-images.githubusercontent.com/13814358/80522653-358c4280-898d-11ea-969e-245255272756.jpg)

It seems to peak rather consistently around 50k iterations, but it's just not quite able to make results that are sufficiently convincing to me (I know that I will never get perfection, with proper letters and all, but I was hoping for crisper definitions of buildings and streets at least!)

Do you have any ideas on what might help? If you want, I could give you access to my source data folder if you wanted to look at it in closer detail

**Comment by lucidrains** [comment]
@iboates perfect timing! I'm about to add an experimental feature that may (or may not) help you train for longer and achieve more detail! you are my perfect guinea pig :)

**Comment by lucidrains** [comment]
leave this open, i'll leave you with instructions by end of day

**Comment by iboates** [comment]
That's great. I'm also researching some options for more efficient training - do you use AWS for training anything? I was thinking about buying some time on an EC2 GPU instance.

**Comment by lucidrains** [comment]
@iboates in the end, i found it most cost effective just to invest in a couple top-of-the-line GPUs

**Comment by lucidrains** [comment]
@iboates what resolution is your map data trained on?

**Comment by iboates** [comment]
I'm doing 256x256, that size seemed sufficient to capture the map features I wanted at an appropriate level of detail. I was hoping to one day drop some big bucks and go all-out on a 1024x1024 model, once I was sure that the process would work.

**Comment by lucidrains** [comment]
@iboates 1024x1024 is out of reach for most people, even for people with a ton of compute

256x256 is good! let me get back to you on that new feature that may or may not work lol

**Comment by lucidrains** [comment]
@iboates the feature is ready! to try it, just upgrade the package and add a `--cl-reg` flag. it should take slightly longer to train, but if it works as expected on your end, it should train for longer, and perhaps result in better quality

**Comment by iboates** [comment]
I am trying it and it seems to make it take approximately 5 iterations per second, as opposed to (if I recall correctly) about 1.8 iterations per second without the flag. I think in order to train this I will have to deploy to a paid solution or try to get my hands on a fancy gaming laptop at my office (which is hard now because of the quarantine...)

**Comment by lucidrains** [comment]
yup! that sounds about right! let me know :)
