### ISSUE TITLE
Embed Image

### ISSUE THREAD

**Issue by john-rocky** [lucidrains/stylegan2-pytorch#53]
Thank you for your great project.
I want to do like this image.
what should I do?
![EWWVv45UYAEoNkA (1)](https://user-images.githubusercontent.com/23278992/80749663-bef46e00-8b61-11ea-9a00-e9daa00b9e1a.jpeg)

**Comment by dancrew32** [comment]
I've seen this configuration for crosstabulating images and animating them in stargan https://github.com/clovaai/stargan-v2 haven't seen a stylegan2 configuration that does this.

**Comment by yuanlunxi** [comment]
hi ,do you know the argment 'fp16' mean?
