### ISSUE TITLE
Does it do automatic image augmentation?

### ISSUE THREAD

**Issue by iboates** [lucidrains/stylegan2-pytorch#55]
I was just wondering if this implementation does any kind of automatic image augmentation, shearing, tinting, flipping, anything like that.

**Comment by lucidrains** [comment]
IS it working??

**Comment by iboates** [comment]
No I was just asking so that I knew if I should do some myself or not.

Right now I am having a rather frustrating issue with a new cloud service provider, it seems that they only provide instances equipped with Ubuntu 16.04 and Python 3.5. I am struggling to install a virtual env of Python 3.6 and have it still able to run the executable, because it is generated by fire in a weird way that I do not understand. Do you think it would be possible to publish a version that did not use fire?

**Comment by lucidrains** [comment]
@iboates Ohh, sorry, I thought you were asking about the new experimental feature, where augmentation is involved there (random crop and color jitter)

I included the only augmentation available in Stylegan2, which is a mirror flip across the horizontal axis, and I believe I also randomly crop and resize as well. There isn't a lot of other augmentations that will be too helpful for training GANs.

**Comment by iboates** [comment]
I see. Right now I am still fighting with the install. It seems that in its current state, this repo is very sensitive to changes in the Python version and must be pegged at exactly Python 3.6.9.

I get to the point where I am able to launch the executable, but then it tells me that there is no GPU available, where there are obviously 4:

```
ubuntu@<my server ip>:~$ python3.6
Python 3.6.9 (default, May  2 2020, 09:29:09) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stylegan2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'stylegan2'
>>> import stylegan2_pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/stylegan2_pytorch/__init__.py", line 1, in <module>
    from stylegan2_pytorch.stylegan2_pytorch import Trainer, StyleGAN2, NanException
  File "/usr/local/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 35, in <module>
    assert torch.cuda.is_available(), 'You need to have an Nvidia GPU with CUDA installed.'
AssertionError: You need to have an Nvidia GPU with CUDA installed.
>>> import torch
>>> torch.cuda.is_available()
False
>>> torch.backends.cudnn.enabled
True
>>> quit()
ubuntu@<my server ip>:~$ nvidia-smi
Sat May  2 09:41:18 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:05:00.0 Off |                  N/A |
| 20%   45C    P8    10W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:07:00.0 Off |                  N/A |
| 20%   44C    P8    10W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 00000000:09:00.0 Off |                  N/A |
| 20%   32C    P8    10W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 00000000:0B:00.0 Off |                  N/A |
| 20%   49C    P8    10W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
ubuntu@<my server ip>:~$ 
```

I'm not sure if you can make anything of this, I think it might have to do with the native installation of the VM offered by the server provider. But it seems that `torch.cuda.is_available()` returns `False` while `torch.backends.cudnn.enabled` returns True.

**Comment by lucidrains** [comment]
Hmm, maybe this thread will help https://forums.fast.ai/t/torch-cuda-is-available-returns-false/16721/28

**Comment by iboates** [comment]
I'm not sure how much I can mess around with the dependencies, since you have them set up the way you need them in your setup.py already.

**Comment by iboates** [comment]
I do see now however that the version of CUDA they hav installed is V9.0.176. Do you have any idea if that is compatible with the version of Pytorch that your are using?

**Comment by iboates** [comment]
Running the solution in the link you posted to downgrade the cuda driver to 9.0 will also either downgrades pytorch or installs another version of it via a conda channel under than name `pytorch` (when installing via pip, i.e. by installing this repo, it is called `torch`)

I don't know, I can't do this any more today but I am worrying that this is simply too bleeding edge for this provider.
