### ISSUE TITLE
Does it work at all with CUDA 9.0?

### ISSUE THREAD

**Issue by iboates** [lucidrains/stylegan2-pytorch#57]
I am very confused about pytorch vs. torch. It seems that this repository uses torch, and not pytorch. What is the difference? The server that I have provisioned comes pre-installed with CUDA 9.0. But it seems that installing this repo brings torch, which will do so with drivers for CUDA 10.0. There is [a page](https://pytorch.org/get-started/previous-versions/) which is supposed to hold older versions of pytorch and torch, but they seem to be all mixed up with one another, and worse is that there appears to be no combination of torch and CUDA 9.0, only pytorch and CUDA 9.2. And this repository is using torch. Am I out of luck here? Do the CUDA drivers themselves need to be upgraded for this to work?

**Comment by lucidrains** [comment]
I just relaxed the requirements for pytorch. Could you try installing the library again?

**Comment by iboates** [comment]
I'll give it a try. Last night after several hours in dependency hell I managed to get... something working, but it was rough. Basically I could only get the repo as of version 0.6.1 working, and even then only by cloning the git repo and installing and selectively downgrading selective repos, and then running it without fire by manually changing the parameters in main.py and calling it directly with python.

I was having a lot of trouble with the new cl_reg feature, specifically it kept whining that it couldn't satisfy the requirement for pytorch once I downgraded it for it to be compatible with CUDA 9.0. Hence why I pinned this repo's version at 0.6.1.

I'm not publishing these steps "officially" yet as I want to make sure I can replicate them. Also, hopefully with some tweaking the process for training with CUDA 9.0 can be made a bit less painful:

```
#    1  wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
#    3  bash Anaconda3-2020.02-Linux-x86_64.sh
#    6  source ~/.bashrc
#   30  conda create --name training python=3.6.9
#   31  conda activate training
#   32  conda install pytorch torchvision cudatoolkit=9.0 -c pytorch
#   35  pip install torch_optimizer
#   38  pip install retry
#   70  pip install tqdm
#   78  pip install pillow==6.2.1
#   39  git clone https://github.com/lucidrains/stylegan2-pytorch.git
#   73  mv stylegan2_pytorch ../../stylegan2-pytorch/main.py
#   80  git checkout 2db7a548204b4b60e97a266f6036f93af2ae3cde
#  107  python main.py 
```

So I decided to take a break from the map GAN until I can figure out how to get cl_reg working (since i already know it just collapses around iteration 70k) and decided to try something else I was cooking up - nighttime cityscapes. It's still training but here's a look at iteration 49:

![49](https://user-images.githubusercontent.com/13814358/80909197-d0d33e00-8d26-11ea-85fd-3eca5bc0543c.jpg)

I can't describe how nice it is to be able to let this run and not have to babysit a browser window and a 15GB Google Drive, and then get kicked off every ten hours and have to wait 24 hours before I'm allowed to train again.

**Comment by iboates** [comment]
By the way I started re-training because I realized I left the image size at 128. Oops.

At 256 the speed seems comparable to Google Colab, which is not unexpected since this repo only uses one GPU from what I understand? Do you know if it will ever by multi-GPU compatible? Doing so would probably make significantly more viable for cloud deployments, the one I am using has 4 GPUs but it can only make use of one.

**Comment by lucidrains** [comment]
@iboates I do wish to make this multi-GPU compatible at some point, with Microsoft's Deepspeed framework. But I'm not sure if it will be as friendly as a command line tool (as you would need to install Deepspeed and setup the config). Let me chew on that for a bit more though.

Let me know how it all turns out. I can rewrite the `cl-reg` experimental feature so it drops its dependency on the library that's forcing Torch to be the newest version.

**Comment by iboates** [comment]
For the time being I seem to be able to run version 0.6.1, albeit with some manual hackery, and I am interested in trying the cl_reg feature, although I will probably have to keep the model at 128x128. I also came across some interesting documentation from the cloud service provider which may be able to upgrade CUDA from the default 9.0 install to 10.0, but I have to look into it more, and I would like to let this city model train for a few more days before I drop it.

I think that installing external software should not be too much of a problem for my use case since I effectively have root access over the machines that I can provision, but a setup guide is always nice.

Multi-GPU support would be a very very good improvement to this project in my opinion. Most cloud providers seem to scale quite aggressively horizontally rather than vertically, so there are usually options for deploying larger groups of the same GPU rather than upgrading to a new model. So that means that the repo is currently rather limited on this playing field, as upgrading the hardware gets no real benefit. I'm not trying to criticize the work or anything, I just think that multi-GPU support would make cloud deployments quite significantly more viable.

I am really not well versed on machine learning concepts (I only understand the basics at a very high level), but if there is any way that I could help with enabling multi-GPU support I would be happy to try.
