### ISSUE TITLE
What Version of Cuda

### ISSUE THREAD

**Issue by jyu041** [lucidrains/stylegan2-pytorch#58]
Hi, im sorry if this sounds stupids, but what version of Cuda is being used for this repo? Is it cuda 10 or something? because cuda has got multiple versions and Im running on a google colab page, but seems like the speed is not like what I expected. Please help :D

**Comment by lucidrains** [comment]
@jyu041 I've relaxed the restrictions on pytorch, so it should work with either 9 or 10

**Comment by jyu041** [comment]
Thank you very much!
