### ISSUE TITLE
How to run the .pt?

### ISSUE THREAD

**Issue by albusdemens** [lucidrains/stylegan2-pytorch#6]
Hi, congrats for the nice work! I'm trying your code and I was wondering whether you have any suggestion on how to run the .pt snapshot files and generate some test images. Thanks!

**Comment by lucidrains** [comment]
Hi! I was actually waiting for more interest before building that portion :) do you have coding experience, or would you like a command line tool. how do you envision using the CLI to generate the image(s)?

**Comment by albusdemens** [comment]
Hi, thanks for the quick reply! I have a research background and I'm learning how to work with PyTorch. Still far from being a wizard though. A CLI would be fantastic, if it doesn't take you too long! Otherwise feel free to point to relevant examples ;-)

**Comment by lucidrains** [comment]
@albusdemens I'll think of something!

**Comment by lucidrains** [comment]
I'm back! I added a `--generate` flag to the command line for now, which will simply generate some images with a timestamp in the results directory. Let me know if that works for you!

**Comment by albusdemens** [comment]
Wonderful! Thanks heaps!!!

**Comment by albusdemens** [comment]
That's an elegant solution btw... I'm starting to understand how you used `stylegan2_pytorch.py`. I might come back with another questions but I'll do my homeworks first. Thanks again!

**Comment by albusdemens** [comment]
Hi again, I am training an agent to generate 512x512 images and I am trying to display intermediate results using the `--generate` flag. It looks like something is off (see errors [here](<script src="https://gist.github.com/albusdemens/170905c5f565d318443e79d8f21dbb64.js"></script>)). Am I doing something wrong? The command I use is `stylegan2_pytorch --generate`.
