### ISSUE TITLE
How to generate a video?

### ISSUE THREAD

**Issue by nikmel2803** [lucidrains/stylegan2-pytorch#65]
Hi!
I’ve been researching how to generate such a video using StyleGAN2 and your implementation for several days, but have not yet found a solution. I have run out of ideas. I already have trained models and understand how to generate images (thanks to your code :D).
Please, can you give me any ideas about how to achieve the desired result?https://www.youtube.com/watch?v=6E1_dgYlifc

**Comment by newcarrotgames** [comment]
AFAIK, the video was created by using specific latent space input vectors, saving the results, and then piecing the images together in a video by another tool. You can read about this on the web: https://machinelearningmastery.com/how-to-interpolate-and-perform-vector-arithmetic-with-faces-using-a-generative-adversarial-network/

There are also youtube tutorials that show how to do this.

**Comment by nikmel2803** [comment]
Thanks a lot!
I'll continue to study this topic and try to write my results here

**Comment by lucidrains** [comment]
@nikmel2803 Hi Nikita! Thank you for your interest! I will add a way to generate the interpolation video in due time (or if you can beat me to it with a PR) :)

**Comment by lucidrains** [comment]
You will need to use something like https://discuss.pytorch.org/t/help-regarding-slerp-function-for-generative-model-sampling/32475 to get a set of latents, get the outputs, and then stitch together the images into a video or gif through ffmpeg or PIL

**Comment by lucidrains** [comment]
added the feature in `0.12.0`! just use the `--generate-interpolation` flag

**Comment by nikmel2803** [comment]
It works amazingly!
Thank you so much
https://drive.google.com/file/d/1JAmbMEal5RtaJlvJ4m834f-X68BOMnpf/view?usp=sharing

**Comment by lucidrains** [comment]
@nikmel2803 oh wow! who is that?

**Comment by nikmel2803** [comment]
I trained the neural network with the photos of the victims of the [Gulag](https://en.wikipedia.org/wiki/Gulag) (dataset collected from this [site](https://ru.openlist.wiki/Категория:Фотографии))

**Comment by lucidrains** [comment]
@nikmel2803 morbid, but cool!

**Comment by nikmel2803** [comment]
This is for a diploma)
