### ISSUE TITLE
ema_inplace() missing 1 required positional arguments:"decay"

### ISSUE THREAD

**Issue by Johnson-yue** [lucidrains/stylegan2-pytorch#66]
ema_inplace() need 3 arguments
but In ema_inplace_module() only input 2 arguments into ema_inplace
https://github.com/lucidrains/stylegan2-pytorch/blob/09189e0aed02c54a6c3c53c948997dae641f67cc/stylegan2_pytorch/stylegan2_pytorch.py#L495-L496

https://github.com/lucidrains/stylegan2-pytorch/blob/09189e0aed02c54a6c3c53c948997dae641f67cc/stylegan2_pytorch/stylegan2_pytorch.py#L181

https://github.com/lucidrains/stylegan2-pytorch/blob/09189e0aed02c54a6c3c53c948997dae641f67cc/stylegan2_pytorch/stylegan2_pytorch.py#L172

**Comment by lucidrains** [comment]
ah yes, you are right, fixed in the latest commit

**Comment by Johnson-yue** [comment]
would you update the pypi to 0.7.2??

**Comment by lucidrains** [comment]
@Johnson-yue I already did
