### ISSUE TITLE
How to change the training iterations?

### ISSUE THREAD

**Issue by pyrosoma** [lucidrains/stylegan2-pytorch#68]
I trained 3800 images with 128x128 resolution. It assgined 150K training iterations for this project. As far as I know, increasing training iterations could increase generation output quality. So, I am trying to train the project over 300k iterations instead of default 150k iterations.

Is there any training parameter for this purpose?

**Comment by lucidrains** [comment]
yup! it is `--num-train-steps`, and you won't have to retrain from scratch, just increase the number!

**Comment by pyrosoma** [comment]
Got it! Thank you very much!
