### ISSUE TITLE
Recent push seems to yield strange results

### ISSUE THREAD

**Issue by pcicales** [lucidrains/stylegan2-pytorch#72]
I updated the code to deal with the decay error you addressed in the recent patch. Now however, this is my output after quite a bit of training (previously much better results by this checkpoint on the same data):

![15-ema](https://user-images.githubusercontent.com/9851953/83360566-d9c82700-a347-11ea-9a94-1eb9158d9f2f.jpg)

This is on pictures of faces. Any advice?

**Comment by lucidrains** [comment]
@pcicales hmm, what does your losses look like?

**Comment by pcicales** [comment]
@lucidrains this was with default settings and non of the experimental methods active.

**Comment by lucidrains** [comment]
@pcicales I'm not sure, it seems to be working fine for me (i'm currently on a training run). we can keep this open and see if anyone else reports the same problem

**Comment by pcicales** [comment]
Ok ill let it keep going and ill report back here.

**Comment by Johnson-yue** [comment]
Hi, I have same question
I am using `pip install stylegan2_pytorch==0.7.2`  
and then I using default parameter test training 
`$ stylegan2_pytorch  --data /path/to/flower102 --name 072_flower102`
and Then I got this result:
![Screenshot from 2020-06-01 18-31-34](https://user-images.githubusercontent.com/10268274/83489370-e03dd680-a4e0-11ea-8b37-90abee106510.png)

6.4W step image :
![64](https://user-images.githubusercontent.com/10268274/83489475-06637680-a4e1-11ea-9042-0c70b4c1a83e.jpg)
![64-ema](https://user-images.githubusercontent.com/10268274/83489480-082d3a00-a4e1-11ea-99b6-8a13cca2699e.jpg)
![64-mr](https://user-images.githubusercontent.com/10268274/83489482-08c5d080-a4e1-11ea-9a98-81208cb43d84.jpg)

Finally result 15W step image
![149](https://user-images.githubusercontent.com/10268274/83489566-2dba4380-a4e1-11ea-8a8e-e75f571c69e0.jpg)
![149-ema](https://user-images.githubusercontent.com/10268274/83489600-3d398c80-a4e1-11ea-99af-00af8c759ea8.jpg)
![149-mr](https://user-images.githubusercontent.com/10268274/83489603-3e6ab980-a4e1-11ea-9633-f191a03dc06b.jpg)

**Comment by pcicales** [comment]
@lucidrains could this be a version issue?

**Comment by lucidrains** [comment]
@Johnson-yue that looks right, you need to train for longer

@pcicales do you remember the last version you had installed that was working? what version of Pytorch are you on?

**Comment by pcicales** [comment]
@lucidrains Its a venv with your requirements installed:
![Screenshot from 2020-06-02 10-08-26](https://user-images.githubusercontent.com/9851953/83536622-17988d00-a4b9-11ea-939f-afa18e3ff29b.png)

**Comment by lucidrains** [comment]
@pcicales Ok, you are on the latest version of pytorch, that's good to know! Do you remember the last working version of stylegan2_pytorch you were using?

**Comment by pcicales** [comment]
@lucidrains hmmm, well I pulled it about a month ago and didn't change it until I ran into the step 20000 issue. I'm not totally sure exactly what version it was, but I believe it was just the version prior to this recent push.

**Comment by lucidrains** [comment]
@pcicales can you try doing a `pip install stylegan2_pytorch==0.9.0.dev0` and see if that version fixes things? I'm just going to start reverting features one by one on that development branch until we find the solution

**Comment by lucidrains** [comment]
@pcicales there was also another big experimental feature I added, feature quantization, and that's the only things I've added in a month or so. So we'll try reverting that next if the EMA thing doesn't work

**Comment by pcicales** [comment]
@lucidrains Ok Ill do that and report back the training results. Thank you so much for your support.

**Comment by lucidrains** [comment]
@pcicales oops, bug :( please use `0.9.1.dev0` !

**Comment by Johnson-yue** [comment]
@lucidrains  what is update for 0.9.1.dev version??

**Comment by Johnson-yue** [comment]
@lucidrains  how many steps  did you use in the training  flower102  dataset ？？

**Comment by lucidrains** [comment]
@Johnson-yue it depends on the size, but for 128x128, <= 100k steps should be enough

**Comment by Johnson-yue** [comment]
@lucidrains  I used default size ,so it is 128 x 128 , and the result is 150k steps finished.
So , I don't know why?

Does you use default parameter can train the 102flower dataset successfully ??

**Comment by lucidrains** [comment]
i think this is fine now
