### ISSUE TITLE
After trained for 250K iterations, the epoch result images looks scrambled.

### ISSUE THREAD

**Issue by pyrosoma** [lucidrains/stylegan2-pytorch#73]
I had trained my dataset around 250K iterations, in Nidia 10.2, cudnn 7.2 environment. 
But the automatic generated images for each epoch look scrambled. (see attached jpegs, they are automatic generated images for epoch 256.)

As I know, the image come with each epoch should mean something. But they are all most the same.

My test data set contains 112 images. All of them are 128x128 resolution.

The training command I used for this project is:

stylegan2_pytorch --data ./images --image-size 128 --batch-size 18 --results_dir ./results --models_dir ./models --num_train_steps 900000

Is there anything wrong?

![256](https://user-images.githubusercontent.com/46179998/83510661-fa3ae180-a4ff-11ea-8950-2a617715b34b.jpg)
![256-ema](https://user-images.githubusercontent.com/46179998/83510667-fc04a500-a4ff-11ea-8c9b-929f6ba18541.jpg)
![256-mr](https://user-images.githubusercontent.com/46179998/83510671-fc9d3b80-a4ff-11ea-983d-2c1c5163a0dd.jpg)

**Comment by lucidrains** [comment]
@pyrosoma Hi! Which version of pytorch are you on?

**Comment by pyrosoma** [comment]
I am using pytorch 1.5.0.
installed by pip.

**Comment by lucidrains** [comment]
@pyrosoma can you do a full uninstall and then reinstall 0.9.0 and let me know if it works or not? also, 100 images is way not enough lol

you should have at least 5000 images

**Comment by pyrosoma** [comment]
Let me approach minimum torch version first.
After several install - uninstall iterations, the lowest version can only be 1.2.0
It seems limited by torchvision , the minimum version is 0.4.2, and mapped torch is 1.2.0
If I use wrong torchvision version, your code will run into exceptions.

by the way, your code need kornia, the minimum version is 0.2.2, this will also limited torch version to 1.1.0 above.

Finally, I use torch 1.2.0 to train again. But automatic generated images are still scrambled. I attach epoch 0 images, and epoch 220 images below. 

epcoh 0 images:

![0](https://user-images.githubusercontent.com/46179998/83992567-53cd6100-a983-11ea-8d4b-f9371b94c563.jpg)
![0-ema](https://user-images.githubusercontent.com/46179998/83992573-562fbb00-a983-11ea-8dea-3439bf2a84e4.jpg)
![0-mr](https://user-images.githubusercontent.com/46179998/83992574-5760e800-a983-11ea-8c34-8fa40e43f911.jpg)


epoch 220 images

![220](https://user-images.githubusercontent.com/46179998/83992645-92631b80-a983-11ea-80b3-d6d106110bc5.jpg)
![220-ema](https://user-images.githubusercontent.com/46179998/83992648-94c57580-a983-11ea-9b51-ea5638b0a266.jpg)
![220-mr](https://user-images.githubusercontent.com/46179998/83992650-95f6a280-a983-11ea-9c15-f360481161b3.jpg)

**Comment by lucidrains** [comment]
pretty sure this is working now
