### ISSUE TITLE
Not the best format for a folder name

### ISSUE THREAD

**Issue by albusdemens** [lucidrains/stylegan2-pytorch#8]
https://github.com/lucidrains/stylegan2-pytorch/blob/7df7f9c21bb807f4e643846060e34274d58df141/bin/stylegan2_pytorch#L43

Maybe something with no spaces and dashes would be better? Example:
`timestamp = now.strftime("%m%d%Y_%H:%M:%S")`

**Comment by lucidrains** [comment]
ok fixed!
