### ISSUE TITLE
Allow transparent interpolation animation generation

### ISSUE THREAD

**Issue by NickAcPT** [lucidrains/stylegan2-pytorch#82]
Currently, when using the `--generate-interpolation` argument, the output GIF file will have a black background if the images have a transparent background.

**Comment by lucidrains** [comment]
ok done https://github.com/lucidrains/stylegan2-pytorch/commit/ad5d07ae0fa311d2f579ba93fd2c3dc166feb2fb

**Comment by NickAcPT** [comment]
That code just converts the transparent images to normal RGB. Won't that cause the generated GIF images to continue having the black background?

**Comment by lucidrains** [comment]
@NickAcPT i don't think GIFs support transparency, which is why you were getting the black background, so I'm converting each frame to an RGB (without the transparency) before the GIF conversion

**Comment by NickAcPT** [comment]
GIFs do support transparency, but I feel like it isn't the best format to be used here.
Is there an easy way to allow users to specify the output format for the interpolation?

Proposed formats:
 - GIF (default)
 - Frame-By-Frame (outputs to a folder instead of directly on the results folder)
 - APNG (animated PNG)
 - WebP (webp is more modern than GIF and supports transparency)

**Comment by lucidrains** [comment]
@NickAcPT oh oops you are right

is your goal simply to have a white background? I think I can get it to work without having to reach for one of these less supported extensions

**Comment by NickAcPT** [comment]
@lucidrains 
> is your goal simply to have a white background?

Not really. My goal is basically to have a way to deal with the transparency of the images myself.
We can probably scrap both APNG and WebP.
Maybe the idea would be to but keep things as they are, revert  ad5d07a, and just implement

**Comment by lucidrains** [comment]
@NickAcPT ok, let's do the frame by frame approach

**Comment by lucidrains** [comment]
@NickAcPT whatcha training on? any cool results?

**Comment by NickAcPT** [comment]
> whatcha training on? any cool results?

Nothing special, really haha. Got bored of seeing the same skins people use in Minecraft (yes, that children game lmao). So, why not try this. Although my results haven't been that great because I've focused much on training the model.

> ok, let's do the frame by frame approach

Thanks so much :D

**Comment by lucidrains** [comment]
@NickAcPT try the new augmentation feature! it should greatly improve results if you are working with a small dataset

**Comment by NickAcPT** [comment]
> try the new augmentation feature! it should greatly improve results if you are working with a small dataset

Well, my dataset has some repeated files (which I'll delete before retraining), but in total I got near to 400k files. It'll just take forever to train since I don't own any good hardware and am instead using Google Colab (yes, shame on me)

**Comment by lucidrains** [comment]
@NickAcPT ohhh 400k is more than enough lol

**Comment by lucidrains** [comment]
@NickAcPT ok done https://github.com/lucidrains/stylegan2-pytorch/commit/e40eb6f471ced10f0ae05e50f6f37a667e0f0bf3

**Comment by NickAcPT** [comment]
Closing as it was implemented. Thanks again for your amazing work!
