### ISSUE TITLE
Scaling the residuals with 1/sqrt(2)

### ISSUE THREAD

**Issue by emirkonuk** [lucidrains/stylegan2-pytorch#88]
Hey, thanks for the repository.

In footnote 3 of the paper Karras mentions a doubling of signal variance. Then, in the official TF code there are the lines
https://github.com/NVlabs/stylegan2/blob/master/training/networks_stylegan2.py#L474
https://github.com/NVlabs/stylegan2/blob/master/training/networks_stylegan2.py#L667
Basically, where there is a residual they scale the sum down by sqrt(2).

I don't know if your omission was intentional, I couldn't find an issue referring to this so I wanted to point it out.

**Comment by lucidrains** [comment]
@emirkonuk hey! I don't think it's super important, but I added it anyways in the latest version!

**Comment by lucidrains** [comment]
https://github.com/lucidrains/stylegan2-pytorch/commit/95f45bc173a2602116b60a1be1d0b1841b1d1014
