### ISSUE TITLE
minibatch stddev layer?

### ISSUE THREAD

**Issue by SongweiGe** [lucidrains/stylegan2-pytorch#93]
Hey I was looking at the offical implementation of styleGAN2, and I found that they kept the minibatch standard deviation layer used in styleGAN: https://github.com/NVlabs/stylegan2/blob/cec605e0834de5404d5c7e5cead7053bdd0e4dde/training/networks_stylegan2.py#L679. But it's not implemented in this repo. JYI, and please feel free to let me know if you want me to help with this.

**Comment by lucidrains** [comment]
@SongweiGe Hi again! I didn't think it was that important of a detail for StyleGan2, but would be happy to add it if you could show me some ablation results that demonstrate otherwise! I was actually planning on looking at PresGAN for mode collapse, but never got around to it

**Comment by SongweiGe** [comment]
I see, that makes sense! Thanks for your explanation. I have tried a similar approach, minibatch discrimination, once and it seemed help. I will keep you updated if I have any new findings on using minibatch stddev layer. : )
