### ISSUE TITLE
not checkpointing amp?

### ISSUE THREAD

**Issue by GetsEclectic** [lucidrains/stylegan2-pytorch#99]
Not sure what the consequences of not checkpointing amp are, happy to add this if it makes sense.

https://nvidia.github.io/apex/amp.html#checkpointing

**Comment by lucidrains** [comment]
@GetsEclectic ohh oops you are correct! I'll get this fixed this week!

**Comment by lucidrains** [comment]
@GetsEclectic done! https://github.com/lucidrains/stylegan2-pytorch/releases/tag/0.17.12

**Comment by GetsEclectic** [comment]
Awesome, thanks!
